### ISSUE TITLE
Can you send me the outzzz code?

### ISSUE THREAD

**Issue by jjh4568520** [Ryzhehvost/BoosterCreator#19]
Can you send me the outzzz code? pls.....
leterppergou@163.com

**Comment by woctezuma** [comment]
https://github.com/Ryzhehvost/BoosterCreator/tree/4eeb53a34eda528232483b01273cd00577be8801

**Comment by Ryzhehvost** [comment]
As @woctezuma mentioned correctly - this is github, full repository history is available to you, you can clone this repo and checkout any commit you want.

**Comment by jjh4568520** [comment]
May I ask how to view historical works of Outzzz

**Comment by Ryzhehvost** [comment]
Learn how to use git and github first. 
You can go to https://github.com/Ryzhehvost/BoosterCreator/commits/master to see the list of commits. You can find last commit from Outzzz - it will be the time where I made this fork. 
Or, you can go to https://github.com/Ryzhehvost/BoosterCreator/network to see graphical representation of the same, each dot represents commit, you can hover it to see the author and then click on it to view changes.
Or, and imho it's the best way, you can do `git clone  https://github.com/Ryzhehvost/BoosterCreator.git` - you will get a copy of this repository on your hard disk. Open the folder with repository and do `git log` - it will show you the list of all commits. Find the last one from Outzzz, and copy it's hash. Then do `git checkout <HASH>`, where instead of `<HASH>` put the hash you copied - voila, your folder now contains the state of last Outzzz commit before the fork.
Hope this short introduction is enough for you. The rest you will find in git documentation https://git-scm.com/doc and github documentation https://docs.github.com

**Comment by woctezuma** [comment]
I realize it is also your "clean" branch: https://github.com/Ryzhehvost/BoosterCreator/tree/clean

**Comment by jjh4568520** [comment]
What I mean is, have you saved his other projects? Except for BoosterCreator

sorry for my english

**Comment by Ryzhehvost** [comment]
No, I don't have any other projects from Outzzz.
